language: python
cache: pip

sudo: required

python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  - "3.5"
  #- "3.5-dev"
  #- "nightly"

install:
  - sudo apt-get install -y libvirt-bin libvirt-dev python-libvirt
  - python setup.py develop

  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements-py2.txt; fi
  - pip install -r requirements-dev.txt
  - cp migrationmonitor/settings.py.template migrationmonitor/settings.py

script:
  - flake8 tests migrationmonitor
  - pytest
