language: python

sudo: required

python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
  # - "3.5-dev"
  # - "nightly"

install:
  - sudo apt-get install -y libvirt-bin libvirt-devel
  - pip install libvirt-python
  - python setup.py develop

script:
  - which migrationmonitor
  - echo OK

