language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
  # - "3.5-dev"
  # - "nightly"

install:
  - sudo apt-get install -y qemu-kvm libvirt-bin virt-manager

script:
  - virsh -c qemu:///system list

