---
# tasks file for telegraf role
#

- name: fetch telegraf installation package | Debian
  get_url: url=http://get.influxdb.org/telegraf/telegraf_{{ telegraf_version }}_amd64.deb dest=/tmp/telegraf_{{ telegraf_version }}_amd64.deb mode=0440

- name: install telegraf package | Debian
  apt: deb=/tmp/telegraf_{{ telegraf_version }}_amd64.deb

- name: start telegraf service and ensure that it is enabled
  service: name=telegraf enabled=yes state=started

- set_fact: config_template="telegraf.conf.j2"

- name: Generate telegraf config from template
  template: src="{{ config_template }}" dest=/etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
