---
# tasks for monitor role

- name: check destination directory for migration-monitor
  stat: path={{ work_dir }}
  register: work_dir_st

- name: Create destination directory
  file: path={{ work_dir }} state=directory
  when: work_dir_st.stat.islnk is not defined

- name: Install git
  apt: name=git

- name: Git clone migration-monitor from github
  git: repo={{ source_repo }} version={{ source_branch }} dest={{ work_dir }}

- name: Generate settings.py from template
  template: src="settings.py.j2" dest="{{ work_dir }}/migrationmonitor/settings.py"

- name: Create virtualenv
  command: virtualenv .venv
  args:
    chdir: "{{ work_dir }}"
    creates: "{{ work_dir }}/{{virtualenv_name}}"
  when: work_dir_st.stat.islnk is not defined

- name: install libvirt-python
  pip: name=libvirt-python virtualenv="{{ work_dir }}/{{virtualenv_name}}"
  when: work_dir_st.stat.islnk is not defined
  
- name: Setup monitoring tool
  command: "{{ work_dir }}/{{virtualenv_name}}/bin/python ./setup.py develop"
  args:
    chdir: "{{ work_dir }}"
  when: work_dir_st.stat.islnk is not defined

- name: check if monitor is running
  stat: path="{{ monitoring_pid }}"
  register: st_pid

- name: Kill monitoring process
  command: "pkill -F {{ monitoring_pid }}"
  when: st_pid.stat.islnk is defined

- name: Run monitoring
  command: "{{ work_dir }}/{{virtualenv_name}}/bin/python migrationmonitor/main.py"
  args:
    chdir: "{{ work_dir }}"
