---
- hosts: hard
  vars:
    nova_conf: /etc/nova/nova.conf
    
    # nova_compress: yes
    # nova_autoconverge: yes
    nova_default_flags: VIR_MIGRATE_UNDEFINE_SOURCE,VIR_MIGRATE_PEER2PEER,VIR_MIGRATE_LIVE,VIR_MIGRATE_PERSIST_DEST
  
  remote_user: stack
  become_method: sudo

  tasks:
  - set_fact:
      compressed_flag: ",VIR_MIGRATE_COMPRESSED"
      when: nova_compress

  - set_fact:
      autoconverge_flag: ",VIR_MIGRATE_AUTO_CONVERGE"
      when: nova_autoconverge

  - name: Backup nova.conf
    command: "cp -f {{ nova_conf }} {{ nova_conf }}.bak"
    become: yes
  - name: Set default flags
    command: "sed -i 's/live_migration_flag=.*$/live_migration_flag={{ nova_default_flags }}{{ compressed_flag | default(\"\") }}{{ autoconverge_flag | default(\"\") }}/g' {{ nova_conf }}"
    become: yes

  - name: Send Ctrl-C to n-cpu screen of devstack
    shell: "screen -X at n-cpu stuff $'\\003'"
    become: no

  - name: Restart n-cpu 
    shell: "screen -X at n-cpu stuff $'\\033[A\\015'"
    become: no
