---
# Vagrant debug
# 
# - hosts: all
#   sudo: yes
#   roles:
#   - telegraf
#   - monitor

- hosts: hard
  remote_user: root
  roles:
  - telegraf
  - monitor

- hosts: virtual
  sudo: yes
  roles:
  - telegraf
